apiVersion: v1
kind: Service
metadata:
  name: dbc-config
  namespace: ${k8s_ns}
  labels:
    app: dbc-config
spec:
  type: NodePort
  sessionAffinity: None
  ports:
    - port: 30170
      targetPort: 30170
      nodePort: 30170
      protocol: TCP
      name: restful
  selector:
    app: dbc-config

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: dbc-config-deployment
  namespace: ${k8s_ns}
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      name: dbc-config
  template:
    metadata:
      labels:
        name: dbc-config
        app: dbc-config
    spec:
      restartPolicy: Always
      volumes:
        - name: app-logs
          hostPath:
            path: /tmp/apps/dbc-config/logs
      containers:
        - name: dbc-config
          image: ${docker_prefix}/dbc-config:${tag}
          imagePullPolicy: Always
          livenessProbe:
            tcpSocket:
              port: 30170
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 240
          readinessProbe:
            tcpSocket:
              port: 30170
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 240
          resources:
            requests:
              cpu: '1'
              memory: 800Mi
            limits:
              cpu: '1'
              memory: 1Gi
          volumeMounts:
            - mountPath: /opt/app/dbc-config/logs
              name: app-logs
          ports:
            - containerPort: 30170
          env:
            - name: spring_profiles_active
              value: "${spring_profiles_active}"
          command: [ "java" ]
          args: [ "-Xmx800m","-Xms800m","-DAPP_SN=h-dbc","-Dspring.profiles.active=${spring_profiles_active}", "-Dspring.main.allow-bean-definition-overriding=true","-Dreactor.netty.http.server.accessLogEnabled=true","-Dfile.encoding=utf-8","-XX:+UseG1GC","-XX:MaxGCPauseMillis=100", "-XX:MetaspaceSize=128m", "-XX:MaxMetaspaceSize=256m", "-XX:+PrintGCDetails", "-XX:+PrintGCDateStamps", "-Xloggc:/opt/app/dbc-config/gc.log", "-jar","/opt/app/dbc-config/lib/dbc-config-1.2.jar" ]

