spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    dynamic:
      enabled: true
      base-packages: com.github.hbq969
      default-lookup-key: hikari
    hikari:
      jdbc-url: jdbc:postgresql://docker.for.mac.host.internal:5432/dbc
      driver-class-name: org.postgresql.Driver
      username: admin
      password: 123456
      maximum-pool-size: 10
      minimum-idle: 2
      max-lifetime: 1800000
      connection-test-query: SELECT 1
  mvc:
    interceptors:
      login:
        enabled: true


mybatis:
  mapper-locations:
    - classpath*:mappers/*.xml
    - classpath*:**/mapper/common/*Mapper.xml
    - classpath*:**/mapper/postgresql/*Mapper.xml
  config-location: classpath:jpaConfig-postgresql.xml

operlog:
  enabled: true
  policy: postgresql
  use-default-collect-policy: true
  table-name: log_dbc
  thread-num: 1
  batch-timeout-mills: 10000
  batch-size: 50
  queue-capacity: 5000

tabula:
  enabled: true
  tables:
    - log_dbc